version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: djangoDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d djangoDB"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    container_name: django_app
    build: .
    #command: python manage.py runserver 0.0.0.0:8000 #isn't needed because handled in Dockerfil
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/api/ || exit 1"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
volumes:
  postgres_data: