# Generated by Django 5.2.5 on 2025-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='subdomain',
            field=models.TextField(blank=True),
        ),
    ]
