# Generated by Django 5.2.5 on 2025-09-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_server_subdomain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='subdomain',
            field=models.TextField(blank=True, editable=False, unique=True),
        ),
    ]
